import type { Metadata } from "next";
import { Montserrat, Space_Grotesk } from "next/font/google";
import { cn } from "~/lib/utils";
import "./globals.css";

const fontSans = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["400", "500", "600", "700"],
});

const fontMono = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Lugano timetable",
  description: "Generated by create next app",
  icons: { icon: "/favicon.ico" },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          fontSans.variable,
          fontMono.variable,
          "min-h-screen bg-background font-sans antialiased mx-auto max-w-md w-full flex flex-col h-screen overflow-y-scroll"
        )}>
        {children}
      </body>
    </html>
  );
}
